name: "yc-install"
description: "deploy"
inputs:
  SA_KEY:
    description: "Yandex cloud service account private key. No logging in if parameter is not provided."
    required: false
    default: ""

branding:
  icon: "terminal"
  color: "blue"
runs:
  using: "composite"
  steps:
    - name: Get latest yc version number
      shell: bash
      id: version
      run: |
        echo "::group:: Get latest yc version"
        LATEST_YC_VERSION=$(curl -s --fail https://storage.yandexcloud.net/yandexcloud-yc/release/stable)
        echo "YC latest version: $LATEST_YC_VERSION"
        echo "::endgroup::"
        echo "LATEST_YC_VERSION=$LATEST_YC_VERSION" >> $GITHUB_OUTPUT

    - name: Cache yc binary
      uses: actions/cache@v4
      id: cache-yc-cli
      with:
        path: /usr/local/bin/yc
        key: yc-cli-${{ steps.version.outputs.value }}

    - name: Get yc binary if cache miss
      if: steps.cache-yc-cli.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo Downloading yc cli version ${{ needs.version.outputs.LATEST_YC_VERSION }}
        sudo curl --fail "https://storage.yandexcloud.net/yandexcloud-yc/release/${{ needs.version.outputs.LATEST_YC_VERSION }}/linux/amd64/yc" -o /usr/local/bin/yc

    - name: Set permissions for yc cli binary
      shell: bash
      run: sudo chmod a+rx /usr/local/bin/yc

    - name: Authorize service account
      if: ${{ inputs.SA_KEY }}
      shell: bash
      run: yc config set service-account-key <(echo '${{ inputs.SA_KEY }}')
